name: Build Wheels

on:
  push:
    branches:
      - main  # Adjust to match your primary branch name

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - runtime: linux-x64
            os: ubuntu-latest
            python-version: '3.8'
            manylinux: '2_28'
          - runtime: linux-x64
            os: ubuntu-latest
            python-version: '3.9'
            manylinux: '2_28'
          - runtime: linux-x64
            os: ubuntu-latest
            python-version: '3.10'
            manylinux: '2_28'
          - runtime: linux-x64
            os: ubuntu-latest
            python-version: '3.11'
            manylinux: '2_28'
          - runtime: win-x64
            os: windows-2019
            python-version: '3.8'
          - runtime: win-x64
            os: windows-2019
            python-version: '3.9'
          - runtime: win-x64
            os: windows-2019
            python-version: '3.10'
          - runtime: win-x64
            os: windows-2019
            python-version: '3.11'
          - runtime: osx-x64
            os: macOS-latest
            python-version: '3.8'
          - runtime: osx-x64
            os: macOS-latest
            python-version: '3.9'
          - runtime: osx-x64
            os: macOS-latest
            python-version: '3.10'
          - runtime: osx-x64
            os: macOS-latest
            python-version: '3.11'
          - runtime: osx-arm64
            os: macOS-latest
            python-version: '3.8'
          - runtime: osx-arm64
            os: macOS-latest
            python-version: '3.9'
          - runtime: osx-arm64
            os: macOS-latest
            python-version: '3.10'
          - runtime: osx-arm64
            os: macOS-latest
            python-version: '3.11'                        
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.os != 'ubuntu-latest'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin
        run: pip install maturin

      - name: Build wheel (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
         docker run --rm -v $(pwd):/io -w /io quay.io/pypa/manylinux2014_x86_64 /io/build_wheels.sh

      - name: Build wheel (Windows and macOS)
        if: matrix.os != 'ubuntu-latest'
        run: maturin build --release

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: target/wheels/*.whl

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')  # Only publish on tagged commits
        run: maturin publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
