name: Build Wheels

on:
  push:
    branches:
      - main  # Adjust to match your primary branch name

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.8'
            manylinux: '2014'
          - os: ubuntu-latest
            python-version: '3.9'
            manylinux: '2014'
          - os: ubuntu-latest
            python-version: '3.10'
            manylinux: '2014'
          - os: ubuntu-latest
            python-version: '3.11'
            manylinux: '2014'
          - os: windows-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.9'
          - os: windows-latest
            python-version: '3.10'
          - os: windows-latest
            python-version: '3.11'
          - os: macOS-latest
            python-version: '3.8'
          - os: macOS-latest
            python-version: '3.9'
          - os: macOS-latest
            python-version: '3.10'
          - os: macOS-latest
            python-version: '3.11'
          - os: aarch64-apple-darwin
            python-version: '3.8'
          - os: aarch64-apple-darwin
            python-version: '3.9'
          - os: aarch64-apple-darwin
            python-version: '3.10'
          - os: aarch64-apple-darwin
            python-version: '3.11'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.os != 'ubuntu-latest'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin
        run: pip install maturin

      - name: Build wheel (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux${{ matrix.manylinux }}_x86_64 /io/build_wheels.sh

      - name: Build wheel (Windows and macOS)
        if: matrix.os != 'ubuntu-latest'
        run: maturin build --release

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: target/wheels/*.whl

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')  # Only publish on tagged commits
        run: maturin publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
